Modules/Security/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('security')->group(function() {
    // role route
    Route::get('/', 'RoleController@index');
    Route::resource('role', 'RoleController')
        ->except(['show', 'destroy']);
    Route::get('role/delete/{id}', 'RoleController@delete')
        ->name('role.delete');
    // permission
    Route::get('permission/{id}', 'PermissionController@index')
        ->name('permission.index');
    Route::post('permission/save', 'PermissionController@store');
    // user route
    Route::resource('user', 'UserController')
        ->except(['destory','show']);
    Route::get('user/delete/{id}', 'UserController@delete')
        ->name('user.delete');
    Route::get('user/detail/{id}', 'UserController@detail')
        ->name('user.detail');
    Route::get('user/logout', 'UserController@logout')
        ->name('user.logout');
    Route::get('branch/delete/{id}', 'UserController@delete_branch')
        ->name('branch.delete');
    Route::get('user/branch/add', 'UserController@add_branch')
        ->name('user.branch.add');
    
});

Modules/Security/Http/Controllers/PermissionController.php
<?php

namespace Modules\Security\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use App\Http\Controllers\Right;
use Auth;
use DB;
class PermissionController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware(function ($request, $next) {
            app()->setLocale(Auth::user()->language);
            return $next($request);
        });
    }
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index($id)
    {
        // if(!Right::check('permission', 'l'))
        // {
        //     return view('permissions.no');
        // }
        $this->data['role'] = DB::table('roles')->find($id);
        $this->data['permissions'] = DB::table('permissions')->orderBy('permissions.id', 'ASC')->get();
        $this->data['roles'] = DB::table('roles')->get();
        $this->data['role_id'] = $id;

        if($id != '') {
            $this->data['per_role'] = DB::select('select tb.id, `tb`.insert,
       `tb`.update,
             `tb`.delete,
       `tb`.list,
       `permissions`.`name`, `permissions`.`alias`,
             `permissions`.`id` as permission_id
            from  `permissions`
            left join (select * from `role_permissions` where `role_permissions`.`role_id` = ' . $id . ') tb on `permissions`.id = tb.permission_id
            order by `permissions`.`id` asc');

        }
        return view('security::permissions.index', $this->data);
    }

    public function store(Request $r)
    {
        // if(!Right::check('permission', 'i'))
        // {
        //     return 1;
        // }
        
        $i=0;
        if($r->id>0)
        {
            // update
            $data = array(
                'role_id' => $r->role_id,
                'permission_id' => $r->permission_id,
                'list' => $r->list,
                'insert' => $r->insert,
                'update' => $r->update,
                'delete' => $r->delete
            );
            DB::table('role_permissions')->where('id', $r->id)->update($data);
            $i = $r->id;
        }
        else
        {
            // insert new

            $data = array(
                'role_id' => $r->role_id,
                'permission_id' => $r->permission_id,
                'list' => $r->list,
                'insert' => $r->insert,
                'update' => $r->update,
                'delete' => $r->delete
            );
            $i = DB::table('role_permissions')->insertGetId($data);
        }
        return $i;
    }
}

Modules/Security/Resources/views/permissions/index.blade.php
@extends('layouts.app')
@section('header')
    <strong>Permission</strong>
@endsection
@section('content')
    <div class="card card-gray">
        <div class="toolbox">
            <a href="{{route('role.index')}}" class="btn btn-warning btn-oval btn-sm ">
                <i class="fa fa-reply"></i> Back
            </a>
        </div>
        
        <div class="card-block">
            <p class="text-success">
                Set permission for {{$role->name}}
            </p>
            @csrf
            <table class="table table-sm table-bordered">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Function</th>
                        <th>View</th>
                        <th>Insert</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @php($i=1)
                    @foreach($per_role as $per)
                        <tr role-id="{{$role_id}}" permission-id="{{$per->permission_id}}" id="{{$per->id==''?'0':$per->id}}">
                            <td>{{$i++}}</td>
                            <td>{{$per->alias}}</td>
                            <td>
                                <label>
                                    <input type='checkbox' value="{{$per->list?'1':'0'}}" 
                                        {{$per->list==1?'checked':''}} onchange="save(this)">
                                    
                                </label>

                            </td>
                            <td>
                                <label>
                                    <input type='checkbox' value="{{$per->insert?'1':'0'}}" 
                                    {{$per->insert==1?'checked':''}} onchange="save(this)">
                                    
                                </label>

                            </td>
                            <td>
                                <label>
                                    <input type='checkbox' value="{{$per->update?'1':'0'}}" {{$per->update==1?'checked':''}} onchange="save(this)">
                                    
                                </label>

                            </td>
                            <td>
                                <label>
                                    <input type='checkbox' value="{{$per->delete?'1':'0'}}" 
                                    {{$per->delete==1?'checked':''}} onchange="save(this)">
                                    
                                </label>

                            </td>

                        </tr>
                    @endforeach

                </tbody>
            </table>
        </div>
    </div>
@endsection
@section('js')
    <script src="{{asset('js/role_permission.js')}}"></script>
	<script>
        $(document).ready(function () {
            $("#sidebar-menu li ").removeClass("active open");
			$("#sidebar-menu li ul li").removeClass("active");
			
            $("#menu_security").addClass("active open");
			$("#security_collapse").addClass("collapse in");
            $("#role_id").addClass("active");
			
        })
    </script>
@endsection