Modules/Enrollment/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('enrollment')->group(function() {
    Route::get('/', 'EnrollmentController@index')->name('enrollment.index');
    Route::get('create', 'EnrollmentController@create')->name('enrollment.create');
    Route::post('save', 'EnrollmentController@save')->name('enrollment.save');
    Route::get('edit/{id}', 'EnrollmentController@edit')->name('enrollment.edit');
    Route::post('update', 'EnrollmentController@update')->name('enrollment.update');
    Route::get('delete/{id}', 'EnrollmentController@delete')->name('enrollment.delete');
    // class
    Route::resource('class', 'ClassController')
        ->except(['destroy', 'show']);
    Route::get('class/delete/{id}', 'ClassController@delete')
        ->name('class.delete');
    Route::get('class/detail/{id}', 'ClassController@detail')
        ->name('class.detail');
    Route::post('class/enroll', 'ClassController@enroll')
        ->name('class.enroll');
    Route::get('class/finish/{id}', 'ClassController@finish')
        ->name('class.finish');
    Route::get('class/archive', 'ClassController@archive')
        ->name('class.archive');
    Route::get('class/enrollment/delete/{id}', 'ClassController@delete_enrollment');
});

Modules/Enrollment/Http/Controllers/ClassController.php
<?php

namespace Modules\Enrollment\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use App\Http\Controllers\Right;
use App\Http\Controllers\Helper;
use DB;
use Auth;
class ClassController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware(function ($request, $next) {
            app()->setLocale(Auth::user()->language);
            return $next($request);
        });
    }
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        if(!Right::check('class', 'l')){
            return view('permissions.no');
        }
        $data['classes'] = DB::table('classes')
            ->join('branches', 'classes.branch_id', 'branches.id')
            ->leftJoin('rooms', 'classes.room_id', 'rooms.id')
            ->leftJoin('shifts', 'classes.shift_id', 'shifts.id')
            ->where('classes.active', 1)
            ->where('classes.is_finish', 0)
            ->whereIn('classes.branch_id', Helper::arr_branch())
            ->orderBy('classes.id', 'desc')
            ->select('classes.*', 'branches.name as bname', 'rooms.name as rname',
                'shifts.name as sname')
            ->paginate(config('app.row'));
        return view('enrollment::classes.index', $data);
    }
    public function archive()
    {
        if(!Right::check('class', 'l')){
            return view('permissions.no');
        }
        $data['classes'] = DB::table('classes')
            ->join('branches', 'classes.branch_id', 'branches.id')
            ->leftJoin('rooms', 'classes.room_id', 'rooms.id')
            ->leftJoin('shifts', 'classes.shift_id', 'shifts.id')
            ->where('classes.active', 1)
            ->where('classes.is_finish', 1)
            ->whereIn('classes.branch_id', Helper::arr_branch())
            ->orderBy('classes.id', 'desc')
            ->select('classes.*', 'branches.name as bname', 'rooms.name as rname',
                'shifts.name as sname')
            ->paginate(config('app.row'));
        return view('enrollment::classes.archive', $data);
    }
    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        if(!Right::check('class', 'i')){
            return view('permissions.no');
        }
        $data['rooms'] = DB::table('rooms')
            ->where('active', 1)
            ->whereIn('branch_id', Helper::arr_branch())
            ->get();
        $data['shifts'] = DB::table('shifts')
            ->where('active', 1)
            ->get();
        $data['branches'] = DB::table('branches')
            ->whereIn('id', Helper::arr_branch())
            ->get();
        return view('enrollment::classes.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Response
     */
    public function store(Request $r)
    {
        if(!Right::check('class', 'i')){
            return view('permissions.no');
        }
        $data = array(
            'code' => $r->code,
            'name' => $r->name,
            'room_id' => $r->room,
            'shift_id' => $r->shift,
            'branch_id' => $r->branch_id,
            'start_date' => $r->start_date,
            'end_date' => $r->end_date,
            'start_time' => $r->start_time,
            'end_time' => $r->end_time
        );
        $i = DB::table('classes')->insertGetId($data);
        if($i)
        {
            return redirect()->route('class.detail', $i);
        }
        else{
            session()->flash('error', 'Fail to save data, please check again!');
            return redirect()->route('class.create')
                ->withInput();
        }
    }

    public function detail($id)
    {
        if(!Right::check('class', 'l')){
            return view('permissions.no');
        }
        $data['class'] = DB::table('classes')
            ->join('branches', 'classes.branch_id', 'branches.id')
            ->leftJoin('rooms', 'classes.room_id', 'rooms.id')
            ->leftJoin('shifts', 'classes.shift_id', 'shifts.id')
            ->where('classes.active', 1)
            ->whereIn('classes.branch_id', Helper::arr_branch())
            ->orderBy('classes.id', 'desc')
            ->select('classes.*', 'branches.name as bname', 'rooms.name as rname',
                'shifts.name as sname')
            ->first();
        $enrolls = DB::table('enrollments')
            ->join('students', 'enrollments.student_id', 'students.id')
            ->where('enrollments.class_id', $id)
            ->where('enrollments.active', 1)
            ->select('enrollments.*', 'students.en_name', 'students.kh_name', 'students.gender', 
            'students.phone', 'students.code', 'students.id as sid')
            ->get();
        $arr = array();
        foreach($enrolls as $en)
        {
            array_push($arr, $en->sid);
        }
        $data['students'] = $enrolls;
        $data['sts'] = DB::table('students')
            ->where('active', 1)
            ->whereNotIn('id', $arr)
            ->get();
        return view('enrollment::classes.detail', $data);
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        if(!Right::check('class', 'u')){
            return view('permissions.no');
        }
        $data['rooms'] = DB::table('rooms')
            ->where('active', 1)
            ->whereIn('branch_id', Helper::arr_branch())
            ->get();
        $data['shifts'] = DB::table('shifts')
            ->where('active', 1)
            ->get();
        $data['branches'] = DB::table('branches')
            ->whereIn('id', Helper::arr_branch())
            ->get();
        $data['class'] = DB::table('classes')->find($id);
        return view('enrollment::classes.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function update(Request $r, $id)
    {
        if(!Right::check('class', 'u'))
        {
            return view('permissions.no');
        }
        $data = array(
            'code' => $r->code,
            'name' => $r->name,
            'room_id' => $r->room,
            'shift_id' => $r->shift,
            'branch_id' => $r->branch_id,
            'start_date' => $r->start_date,
            'end_date' => $r->end_date,
            'start_time' => $r->start_time,
            'end_time' => $r->end_time
        );
        $i = DB::table('classes')
            ->where('id', $id)
            ->update($data);
        if($i)
        {
            return redirect()->route('class.detail', $i)
                ->with('success', 'Data has been saved!');
        }
        else{
            session()->flash('error', 'Fail to save data, please check again!');
            return redirect()->route('class.edit', $id)
                ->withInput();
        }
    }

    public function delete($id)
    {
        if(!Right::check('class', 'd')){
            return view('permissions.no');
        }
        $i = DB::table('classes')
            ->where('id', $id)
            ->update(['active'=>0]);
        if($i)
        {
            DB::table('enrollments')
                ->where('class_id', $id)
                ->update(['active'=>0]);

            return redirect()->route('class.index')
                ->with('success', 'Data has been removed!');
        }
        else{
            return redirect()->route('class.index')
                ->with('error', 'Fail to remove data!');
        }
    }
    // enroll new student
    public function enroll(Request $r)
    {
        $class_id = $r->class_id;
        $class = DB::table('classes')->find($class_id);
        $data = array(
            'student_id' => $r->student,
            'class_id' => $r->class_id,
            'shift_id' => $class->shift_id,
            'room_id' => $class->room_id,
            'branch_id' => $class->branch_id,
            'enroll_date' => $r->enroll_date,
            'create_by' => Auth::user()->id
        );
        $i = DB::table('enrollments')->insert($data);
        return redirect()->route('class.detail', $r->class_id)
            ->with('success', 'New student has been enrolled!');
    }
    public function delete_enrollment(Request $r, $id)
    {
        DB::table('enrollments')
            ->where('id', $id)
            ->update(['active'=>0]);
        return redirect()->route('class.detail', $r->cid);
    }
    public function finish($id)
    {
        DB::table('classes')
            ->where('id', $id)
            ->update(['is_finish'=>1]);
        return redirect()->route('class.index')
            ->with('success', 'Data has been saved!');
    }
}

Modules/Enrollment/Resources/views/classes/archive.blade.php
@extends('layouts.app')
@section('header')
    <strong>Classes</strong>
@endsection
@section('content')
                       
    <div class="card card-gray">
        <div class="toolbox">
            <a href="{{route('class.create')}}" class="btn btn-primary btn-oval btn-sm ">
                <i class="fa fa-plus-circle"></i> Create
            </a>
        </div>

        <div class="card-block">
            @component('layouts.coms.alert')
            @endcomponent
            <table class="table table-sm table-bordered">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Code</th>
                        <th>Name</th>
                        <th>Room</th>
                        <th>Shift</th>
                        <th>Date</th>
                        <th>Status</th>
                        <th>Total#</th>
                        <th>Branch</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $pagex = @$_GET['page'];
                    if(!$pagex)
                        $pagex = 1;
                    $i = config('app.row') * ($pagex - 1) + 1;
                    ?>
                    @foreach($classes as $class)
                        <tr>
                            <td>{{$i++}}</td>
                            <td>
                                <a href="{{route('class.detail', $class->id)}}">{{$class->code}}</a>
                            </td>
                            <td>
                                <a href="{{route('class.detail', $class->id)}}">{{$class->name}}</a>
                            </td>
                            <td>{{$class->rname}}</td>
                            <td>
                                {{$class->sname}} <br>
                                <small>{{$class->start_time}} - {{$class->end_time}}</small>

                            </td>
                            <td>
                                {{$class->start_date}} - {{$class->end_date}}
                            </td>
                            <td>
                                {{$class->is_finish?'Finished':'Progress'}}
                            </td>
                            <td>{{$class->bname}}</td>
                            <td>
                                
                                <a href="{{route('class.edit', $class->id)}}" title="Update" class="text-success"><i class="fa fa-edit"></i></a>&nbsp;&nbsp;
                                <a href="{{route('class.delete',$class->id)}}" title="Delete" 
                                    onclick="return confirm('You want to delete?')" class="text-danger"><i class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            {{$classes->links()}} 
        </div>
    </div>
                           
@endsection

@section('js')
	<script>
        $(document).ready(function () {
            $("#sidebar-menu li ").removeClass("active open");
			$("#sidebar-menu li ul li").removeClass("active");
			
            $("#enrollment").addClass("active open");
			$("#enrollment_collapse").addClass("collapse in");
            $("#menu_archive").addClass("active");
			
        })
    </script>
@endsection

Modules/Enrollment/Resources/views/classes/create.blade.php
@extends('layouts.app')
@section('header')
    <strong>Create Class</strong>
@endsection
@section('content')
<form action="{{route('class.store')}}" method="POST">                       
    <div class="card card-gray">
        <div class="toolbox">
            <button type="submit" class="btn btn-sm btn-oval btn-primary">
                <i class="fa fa-save "></i> Save
            </button>
            <button class="btn btn-sm btn-danger btn-oval" type="reset">
                <i class="fa fa-refresh"></i> Cancel
            </button>
            <a href="{{route('class.index')}}" class="btn btn-warning btn-oval btn-sm ">
                <i class="fa fa-reply"></i> Back
            </a>
        </div>
						
        <div class="card-block">
            @component('layouts.coms.alert')
            @endcomponent
            <div class="row">
            <div class="col-md-6">
                {{csrf_field()}}
                <div class="form-group row">
                    <label for="code" class="col-sm-4 form-control-label">Code <span class="text-danger">*</span></label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" id="code" name="code" 
                            value="{{old('code')}}" required autofocus>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="Name" class="col-sm-4 form-control-label">Name <span class="text-danger">*</span></label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" id="Name" name="name"
                            value="{{old('name')}}" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="start_date" class="col-sm-4 form-control-label">Start Date</label>
                    <div class="col-sm-8">
                        <input type="date" class="form-control" id="start_date" name="start_date"
                            value="{{old('start_date')}}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="end_date" class="col-sm-4 form-control-label">End Date</label>
                    <div class="col-sm-8">
                        <input type="date" class="form-control" id="end_date" name="end_date"
                            value="{{old('end_date')}}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="start_time" class="col-sm-4 form-control-label">Start Time</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" id="start_time" name="start_time"
                            value="{{old('start_time')}}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="end_time" class="col-sm-4 form-control-label">End Time</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" id="end_time" name="end_time"
                            value="{{old('end_time')}}">
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group row">
                    <label for="room" class="col-sm-3 form-control-label">Room</label>
                    <div class="col-sm-8">
                        <select name="room" id="room" class="form-control">
                            <option value="0"></option>
                            @foreach($rooms as $b)
                                <option value="{{$b->id}}">{{$b->name}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="shift" class="col-sm-3 form-control-label">Shift</label>
                    <div class="col-sm-8">
                        <select name="shift" id="shift" class="form-control">
                            <option value="0"></option>
                            @foreach($shifts as $b)
                                <option value="{{$b->id}}">{{$b->name}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="branch_id" class="col-sm-3 form-control-label">Branch <span class="text-danger">*</span></label>
                    <div class="col-sm-8">
                        <select name="branch_id" id="branch_id" class="form-control" required>
                            @foreach($branches as $b)
                                <option value="{{$b->id}}">{{$b->name}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>

</form>                            
@endsection

@section('js')
	<script>
        $(document).ready(function () {
            $("#sidebar-menu li ").removeClass("active open");
			$("#sidebar-menu li ul li").removeClass("active");
			
            $("#enrollment").addClass("active open");
			$("#enrollment_collapse").addClass("collapse in");
            $("#menu_class").addClass("active");
			
        })
    </script>
@endsection

Modules/Enrollment/Resources/views/classes/edit.blade.php
@extends('layouts.app')
@section('header')
    <strong>Edit Class</strong>
@endsection
@section('content')
<form action="{{route('class.update', $class->id)}}" method="POST"> 
    @method('PATCH')                      
    <div class="card card-gray">
        <div class="toolbox">
            <button type="submit" class="btn btn-sm btn-oval btn-primary">
                <i class="fa fa-save "></i> Save
            </button>
            <button class="btn btn-sm btn-danger btn-oval" type="reset">
                <i class="fa fa-refresh"></i> Cancel
            </button>
            <a href="{{route('class.index')}}" class="btn btn-warning btn-oval btn-sm ">
                <i class="fa fa-reply"></i> Back
            </a>
        </div>
						
        <div class="card-block">
            @component('layouts.coms.alert')
            @endcomponent
            <div class="row">
            <div class="col-md-6">
                {{csrf_field()}}
                <div class="form-group row">
                    <label for="code" class="col-sm-4 form-control-label">Code <span class="text-danger">*</span></label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" id="code" name="code" 
                            value="{{$class->code}}" required autofocus>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="Name" class="col-sm-4 form-control-label">Name <span class="text-danger">*</span></label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" id="Name" name="name"
                            value="{{$class->name}}" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="start_date" class="col-sm-4 form-control-label">Start Date</label>
                    <div class="col-sm-8">
                        <input type="date" class="form-control" id="start_date" name="start_date"
                            value="{{$class->start_date}}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="end_date" class="col-sm-4 form-control-label">End Date</label>
                    <div class="col-sm-8">
                        <input type="date" class="form-control" id="end_date" name="end_date"
                            value="{{$class->end_date}}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="start_time" class="col-sm-4 form-control-label">Start Time</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" id="start_time" name="start_time"
                            value="{{$class->start_time}}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="end_time" class="col-sm-4 form-control-label">End Time</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" id="end_time" name="end_time"
                            value="{{$class->end_time}}">
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group row">
                    <label for="room" class="col-sm-3 form-control-label">Room</label>
                    <div class="col-sm-8">
                        <select name="room" id="room" class="form-control">
                            <option value="0"></option>
                            @foreach($rooms as $b)
                                <option value="{{$b->id}}" {{$b->id==$class->room_id?'selected':''}}>{{$b->name}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="shift" class="col-sm-3 form-control-label">Shift</label>
                    <div class="col-sm-8">
                        <select name="shift" id="shift" class="form-control">
                            <option value="0"></option>
                            @foreach($shifts as $b)
                                <option value="{{$b->id}}" {{$b->id==$class->shift_id?'selected':''}}>{{$b->name}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="branch_id" class="col-sm-3 form-control-label">Branch <span class="text-danger">*</span></label>
                    <div class="col-sm-8">
                        <select name="branch_id" id="branch_id" class="form-control" required>
                            @foreach($branches as $b)
                                <option value="{{$b->id}}" {{$b->id==$class->branch_id?'selected':''}}>{{$b->name}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>

</form>                            
@endsection

@section('js')
	<script>
        $(document).ready(function () {
            $("#sidebar-menu li ").removeClass("active open");
			$("#sidebar-menu li ul li").removeClass("active");
			
            $("#enrollment").addClass("active open");
			$("#enrollment_collapse").addClass("collapse in");
            $("#menu_class").addClass("active");
			
        })
    </script>
@endsection

Modules/Enrollment/Resources/views/classes/index.blade.php
@extends('layouts.app')
@section('header')
    <strong>Classes</strong>
@endsection
@section('content')
                       
    <div class="card card-gray">
        <div class="toolbox">
            <a href="{{route('class.create')}}" class="btn btn-primary btn-oval btn-sm ">
                <i class="fa fa-plus-circle"></i> Create
            </a>
        </div>

        <div class="card-block">
            @component('layouts.coms.alert')
            @endcomponent
            <table class="table table-sm table-bordered">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Code</th>
                        <th>Name</th>
                        <th>Room</th>
                        <th>Shift</th>
                        <th>Date</th>
                        <th>Status</th>
                        <th>Total#</th>
                        <th>Branch</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    $pagex = @$_GET['page'];
                    if(!$pagex)
                        $pagex = 1;
                    $i = config('app.row') * ($pagex - 1) + 1;
                    ?>
                    @foreach($classes as $class)
                        <tr>
                            <td>{{$i++}}</td>
                            <td>
                                <a href="{{route('class.detail', $class->id)}}">{{$class->code}}</a>
                            </td>
                            <td>
                                <a href="{{route('class.detail', $class->id)}}">{{$class->name}}</a>
                            </td>
                            <td>{{$class->rname}}</td>
                            <td>
                                {{$class->sname}} <br>
                                <small>{{$class->start_time}} - {{$class->end_time}}</small>

                            </td>
                            <td>
                                {{$class->start_date}} - {{$class->end_date}}
                            </td>
                            <td>
                                {{$class->is_finish?'Finished':'Progress'}}
                            </td>
                            <td>{{$class->bname}}</td>
                            <td>
                                
                                <a href="{{route('class.edit', $class->id)}}" title="Update" class="text-success"><i class="fa fa-edit"></i></a>&nbsp;&nbsp;
                                <a href="{{route('class.delete',$class->id)}}" title="Delete" 
                                    onclick="return confirm('You want to delete?')" class="text-danger"><i class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            {{$classes->links()}} 
        </div>
    </div>
                           
@endsection

@section('js')
	<script>
        $(document).ready(function () {
            $("#sidebar-menu li ").removeClass("active open");
			$("#sidebar-menu li ul li").removeClass("active");
			
            $("#enrollment").addClass("active open");
			$("#enrollment_collapse").addClass("collapse in");
            $("#menu_class").addClass("active");
			
        })
    </script>
@endsection